import { CharacterType, CharacterDirection } from '@location-messenger/shared'

export type AnimationName = 'idle' | 'walking'

type ImageSource = ReturnType<typeof require>

export function getCharacterRotation(type: CharacterType, direction: CharacterDirection): ImageSource {
  return (ROTATIONS[type] ?? ROTATIONS['boy_casual'])[direction]
}

export function getCharacterFrames(type: CharacterType, animation: AnimationName, direction: CharacterDirection): ImageSource[] {
  const charFrames = FRAMES[type] ?? FRAMES['boy_casual']
  const animFrames = charFrames[animation] ?? charFrames['idle']
  return animFrames[direction] ?? animFrames['south']
}

const ROTATIONS: Record<CharacterType, Record<CharacterDirection, ImageSource>> = {
  boy_casual: {
    south: require('../assets/characters/boy_casual/rotations/south.png'),
    'south-east': require('../assets/characters/boy_casual/rotations/south-east.png'),
    east: require('../assets/characters/boy_casual/rotations/east.png'),
    'north-east': require('../assets/characters/boy_casual/rotations/north-east.png'),
    north: require('../assets/characters/boy_casual/rotations/north.png'),
    'north-west': require('../assets/characters/boy_casual/rotations/north-west.png'),
    west: require('../assets/characters/boy_casual/rotations/west.png'),
    'south-west': require('../assets/characters/boy_casual/rotations/south-west.png'),
  },
  boy_hiphop: {
    south: require('../assets/characters/boy_hiphop/rotations/south.png'),
    'south-east': require('../assets/characters/boy_hiphop/rotations/south-east.png'),
    east: require('../assets/characters/boy_hiphop/rotations/east.png'),
    'north-east': require('../assets/characters/boy_hiphop/rotations/north-east.png'),
    north: require('../assets/characters/boy_hiphop/rotations/north.png'),
    'north-west': require('../assets/characters/boy_hiphop/rotations/north-west.png'),
    west: require('../assets/characters/boy_hiphop/rotations/west.png'),
    'south-west': require('../assets/characters/boy_hiphop/rotations/south-west.png'),
  },
  boy_formal: {
    south: require('../assets/characters/boy_formal/rotations/south.png'),
    'south-east': require('../assets/characters/boy_formal/rotations/south-east.png'),
    east: require('../assets/characters/boy_formal/rotations/east.png'),
    'north-east': require('../assets/characters/boy_formal/rotations/north-east.png'),
    north: require('../assets/characters/boy_formal/rotations/north.png'),
    'north-west': require('../assets/characters/boy_formal/rotations/north-west.png'),
    west: require('../assets/characters/boy_formal/rotations/west.png'),
    'south-west': require('../assets/characters/boy_formal/rotations/south-west.png'),
  },
  girl_school: {
    south: require('../assets/characters/girl_school/rotations/south.png'),
    'south-east': require('../assets/characters/girl_school/rotations/south-east.png'),
    east: require('../assets/characters/girl_school/rotations/east.png'),
    'north-east': require('../assets/characters/girl_school/rotations/north-east.png'),
    north: require('../assets/characters/girl_school/rotations/north.png'),
    'north-west': require('../assets/characters/girl_school/rotations/north-west.png'),
    west: require('../assets/characters/girl_school/rotations/west.png'),
    'south-west': require('../assets/characters/girl_school/rotations/south-west.png'),
  },
  girl_casual: {
    south: require('../assets/characters/girl_casual/rotations/south.png'),
    'south-east': require('../assets/characters/girl_casual/rotations/south-east.png'),
    east: require('../assets/characters/girl_casual/rotations/east.png'),
    'north-east': require('../assets/characters/girl_casual/rotations/north-east.png'),
    north: require('../assets/characters/girl_casual/rotations/north.png'),
    'north-west': require('../assets/characters/girl_casual/rotations/north-west.png'),
    west: require('../assets/characters/girl_casual/rotations/west.png'),
    'south-west': require('../assets/characters/girl_casual/rotations/south-west.png'),
  },
  girl_career: {
    south: require('../assets/characters/girl_career/rotations/south.png'),
    'south-east': require('../assets/characters/girl_career/rotations/south-east.png'),
    east: require('../assets/characters/girl_career/rotations/east.png'),
    'north-east': require('../assets/characters/girl_career/rotations/north-east.png'),
    north: require('../assets/characters/girl_career/rotations/north.png'),
    'north-west': require('../assets/characters/girl_career/rotations/north-west.png'),
    west: require('../assets/characters/girl_career/rotations/west.png'),
    'south-west': require('../assets/characters/girl_career/rotations/south-west.png'),
  },
}

type FrameMap = Record<AnimationName, Record<CharacterDirection, ImageSource[]>>

const FRAMES: Record<CharacterType, FrameMap> = {
  boy_casual: {
    idle: {
      south: [require('../assets/characters/boy_casual/animations/idle/south_0.png'), require('../assets/characters/boy_casual/animations/idle/south_1.png'), require('../assets/characters/boy_casual/animations/idle/south_2.png'), require('../assets/characters/boy_casual/animations/idle/south_3.png')],
      'south-east': [require('../assets/characters/boy_casual/animations/idle/south-east_0.png'), require('../assets/characters/boy_casual/animations/idle/south-east_1.png'), require('../assets/characters/boy_casual/animations/idle/south-east_2.png'), require('../assets/characters/boy_casual/animations/idle/south-east_3.png')],
      east: [require('../assets/characters/boy_casual/animations/idle/east_0.png'), require('../assets/characters/boy_casual/animations/idle/east_1.png'), require('../assets/characters/boy_casual/animations/idle/east_2.png'), require('../assets/characters/boy_casual/animations/idle/east_3.png')],
      'north-east': [require('../assets/characters/boy_casual/animations/idle/north-east_0.png'), require('../assets/characters/boy_casual/animations/idle/north-east_1.png'), require('../assets/characters/boy_casual/animations/idle/north-east_2.png'), require('../assets/characters/boy_casual/animations/idle/north-east_3.png')],
      north: [require('../assets/characters/boy_casual/animations/idle/north_0.png'), require('../assets/characters/boy_casual/animations/idle/north_1.png'), require('../assets/characters/boy_casual/animations/idle/north_2.png'), require('../assets/characters/boy_casual/animations/idle/north_3.png')],
      'north-west': [require('../assets/characters/boy_casual/animations/idle/north-west_0.png'), require('../assets/characters/boy_casual/animations/idle/north-west_1.png'), require('../assets/characters/boy_casual/animations/idle/north-west_2.png'), require('../assets/characters/boy_casual/animations/idle/north-west_3.png')],
      west: [require('../assets/characters/boy_casual/animations/idle/west_0.png'), require('../assets/characters/boy_casual/animations/idle/west_1.png'), require('../assets/characters/boy_casual/animations/idle/west_2.png'), require('../assets/characters/boy_casual/animations/idle/west_3.png')],
      'south-west': [require('../assets/characters/boy_casual/animations/idle/south-west_0.png'), require('../assets/characters/boy_casual/animations/idle/south-west_1.png'), require('../assets/characters/boy_casual/animations/idle/south-west_2.png'), require('../assets/characters/boy_casual/animations/idle/south-west_3.png')],
    },
    walking: {
      south: [require('../assets/characters/boy_casual/animations/walking/south_0.png'), require('../assets/characters/boy_casual/animations/walking/south_1.png'), require('../assets/characters/boy_casual/animations/walking/south_2.png'), require('../assets/characters/boy_casual/animations/walking/south_3.png'), require('../assets/characters/boy_casual/animations/walking/south_4.png'), require('../assets/characters/boy_casual/animations/walking/south_5.png'), require('../assets/characters/boy_casual/animations/walking/south_6.png'), require('../assets/characters/boy_casual/animations/walking/south_7.png')],
      'south-east': [require('../assets/characters/boy_casual/animations/walking/south-east_0.png'), require('../assets/characters/boy_casual/animations/walking/south-east_1.png'), require('../assets/characters/boy_casual/animations/walking/south-east_2.png'), require('../assets/characters/boy_casual/animations/walking/south-east_3.png'), require('../assets/characters/boy_casual/animations/walking/south-east_4.png'), require('../assets/characters/boy_casual/animations/walking/south-east_5.png'), require('../assets/characters/boy_casual/animations/walking/south-east_6.png'), require('../assets/characters/boy_casual/animations/walking/south-east_7.png')],
      east: [require('../assets/characters/boy_casual/animations/walking/east_0.png'), require('../assets/characters/boy_casual/animations/walking/east_1.png'), require('../assets/characters/boy_casual/animations/walking/east_2.png'), require('../assets/characters/boy_casual/animations/walking/east_3.png'), require('../assets/characters/boy_casual/animations/walking/east_4.png'), require('../assets/characters/boy_casual/animations/walking/east_5.png'), require('../assets/characters/boy_casual/animations/walking/east_6.png'), require('../assets/characters/boy_casual/animations/walking/east_7.png')],
      'north-east': [require('../assets/characters/boy_casual/animations/walking/north-east_0.png'), require('../assets/characters/boy_casual/animations/walking/north-east_1.png'), require('../assets/characters/boy_casual/animations/walking/north-east_2.png'), require('../assets/characters/boy_casual/animations/walking/north-east_3.png'), require('../assets/characters/boy_casual/animations/walking/north-east_4.png'), require('../assets/characters/boy_casual/animations/walking/north-east_5.png'), require('../assets/characters/boy_casual/animations/walking/north-east_6.png'), require('../assets/characters/boy_casual/animations/walking/north-east_7.png')],
      north: [require('../assets/characters/boy_casual/animations/walking/north_0.png'), require('../assets/characters/boy_casual/animations/walking/north_1.png'), require('../assets/characters/boy_casual/animations/walking/north_2.png'), require('../assets/characters/boy_casual/animations/walking/north_3.png'), require('../assets/characters/boy_casual/animations/walking/north_4.png'), require('../assets/characters/boy_casual/animations/walking/north_5.png'), require('../assets/characters/boy_casual/animations/walking/north_6.png'), require('../assets/characters/boy_casual/animations/walking/north_7.png')],
      'north-west': [require('../assets/characters/boy_casual/animations/walking/north-west_0.png'), require('../assets/characters/boy_casual/animations/walking/north-west_1.png'), require('../assets/characters/boy_casual/animations/walking/north-west_2.png'), require('../assets/characters/boy_casual/animations/walking/north-west_3.png'), require('../assets/characters/boy_casual/animations/walking/north-west_4.png'), require('../assets/characters/boy_casual/animations/walking/north-west_5.png'), require('../assets/characters/boy_casual/animations/walking/north-west_6.png'), require('../assets/characters/boy_casual/animations/walking/north-west_7.png')],
      west: [require('../assets/characters/boy_casual/animations/walking/west_0.png'), require('../assets/characters/boy_casual/animations/walking/west_1.png'), require('../assets/characters/boy_casual/animations/walking/west_2.png'), require('../assets/characters/boy_casual/animations/walking/west_3.png'), require('../assets/characters/boy_casual/animations/walking/west_4.png'), require('../assets/characters/boy_casual/animations/walking/west_5.png'), require('../assets/characters/boy_casual/animations/walking/west_6.png'), require('../assets/characters/boy_casual/animations/walking/west_7.png')],
      'south-west': [require('../assets/characters/boy_casual/animations/walking/south-west_0.png'), require('../assets/characters/boy_casual/animations/walking/south-west_1.png'), require('../assets/characters/boy_casual/animations/walking/south-west_2.png'), require('../assets/characters/boy_casual/animations/walking/south-west_3.png'), require('../assets/characters/boy_casual/animations/walking/south-west_4.png'), require('../assets/characters/boy_casual/animations/walking/south-west_5.png'), require('../assets/characters/boy_casual/animations/walking/south-west_6.png'), require('../assets/characters/boy_casual/animations/walking/south-west_7.png')],
    },
  },
  boy_hiphop: {
    idle: {
      south: [require('../assets/characters/boy_hiphop/animations/idle/south_0.png'), require('../assets/characters/boy_hiphop/animations/idle/south_1.png'), require('../assets/characters/boy_hiphop/animations/idle/south_2.png'), require('../assets/characters/boy_hiphop/animations/idle/south_3.png')],
      'south-east': [require('../assets/characters/boy_hiphop/animations/idle/south-east_0.png'), require('../assets/characters/boy_hiphop/animations/idle/south-east_1.png'), require('../assets/characters/boy_hiphop/animations/idle/south-east_2.png'), require('../assets/characters/boy_hiphop/animations/idle/south-east_3.png')],
      east: [require('../assets/characters/boy_hiphop/animations/idle/east_0.png'), require('../assets/characters/boy_hiphop/animations/idle/east_1.png'), require('../assets/characters/boy_hiphop/animations/idle/east_2.png'), require('../assets/characters/boy_hiphop/animations/idle/east_3.png')],
      'north-east': [require('../assets/characters/boy_hiphop/animations/idle/north-east_0.png'), require('../assets/characters/boy_hiphop/animations/idle/north-east_1.png'), require('../assets/characters/boy_hiphop/animations/idle/north-east_2.png'), require('../assets/characters/boy_hiphop/animations/idle/north-east_3.png')],
      north: [require('../assets/characters/boy_hiphop/animations/idle/north_0.png'), require('../assets/characters/boy_hiphop/animations/idle/north_1.png'), require('../assets/characters/boy_hiphop/animations/idle/north_2.png'), require('../assets/characters/boy_hiphop/animations/idle/north_3.png')],
      'north-west': [require('../assets/characters/boy_hiphop/animations/idle/north-west_0.png'), require('../assets/characters/boy_hiphop/animations/idle/north-west_1.png'), require('../assets/characters/boy_hiphop/animations/idle/north-west_2.png'), require('../assets/characters/boy_hiphop/animations/idle/north-west_3.png')],
      west: [require('../assets/characters/boy_hiphop/animations/idle/west_0.png'), require('../assets/characters/boy_hiphop/animations/idle/west_1.png'), require('../assets/characters/boy_hiphop/animations/idle/west_2.png'), require('../assets/characters/boy_hiphop/animations/idle/west_3.png')],
      'south-west': [require('../assets/characters/boy_hiphop/animations/idle/south-west_0.png'), require('../assets/characters/boy_hiphop/animations/idle/south-west_1.png'), require('../assets/characters/boy_hiphop/animations/idle/south-west_2.png'), require('../assets/characters/boy_hiphop/animations/idle/south-west_3.png')],
    },
    walking: {
      south: [require('../assets/characters/boy_hiphop/animations/walking/south_0.png'), require('../assets/characters/boy_hiphop/animations/walking/south_1.png'), require('../assets/characters/boy_hiphop/animations/walking/south_2.png'), require('../assets/characters/boy_hiphop/animations/walking/south_3.png'), require('../assets/characters/boy_hiphop/animations/walking/south_4.png'), require('../assets/characters/boy_hiphop/animations/walking/south_5.png'), require('../assets/characters/boy_hiphop/animations/walking/south_6.png'), require('../assets/characters/boy_hiphop/animations/walking/south_7.png')],
      'south-east': [require('../assets/characters/boy_hiphop/animations/walking/south-east_0.png'), require('../assets/characters/boy_hiphop/animations/walking/south-east_1.png'), require('../assets/characters/boy_hiphop/animations/walking/south-east_2.png'), require('../assets/characters/boy_hiphop/animations/walking/south-east_3.png'), require('../assets/characters/boy_hiphop/animations/walking/south-east_4.png'), require('../assets/characters/boy_hiphop/animations/walking/south-east_5.png'), require('../assets/characters/boy_hiphop/animations/walking/south-east_6.png'), require('../assets/characters/boy_hiphop/animations/walking/south-east_7.png')],
      east: [require('../assets/characters/boy_hiphop/animations/walking/east_0.png'), require('../assets/characters/boy_hiphop/animations/walking/east_1.png'), require('../assets/characters/boy_hiphop/animations/walking/east_2.png'), require('../assets/characters/boy_hiphop/animations/walking/east_3.png'), require('../assets/characters/boy_hiphop/animations/walking/east_4.png'), require('../assets/characters/boy_hiphop/animations/walking/east_5.png'), require('../assets/characters/boy_hiphop/animations/walking/east_6.png'), require('../assets/characters/boy_hiphop/animations/walking/east_7.png')],
      'north-east': [require('../assets/characters/boy_hiphop/animations/walking/north-east_0.png'), require('../assets/characters/boy_hiphop/animations/walking/north-east_1.png'), require('../assets/characters/boy_hiphop/animations/walking/north-east_2.png'), require('../assets/characters/boy_hiphop/animations/walking/north-east_3.png'), require('../assets/characters/boy_hiphop/animations/walking/north-east_4.png'), require('../assets/characters/boy_hiphop/animations/walking/north-east_5.png'), require('../assets/characters/boy_hiphop/animations/walking/north-east_6.png'), require('../assets/characters/boy_hiphop/animations/walking/north-east_7.png')],
      north: [require('../assets/characters/boy_hiphop/animations/walking/north_0.png'), require('../assets/characters/boy_hiphop/animations/walking/north_1.png'), require('../assets/characters/boy_hiphop/animations/walking/north_2.png'), require('../assets/characters/boy_hiphop/animations/walking/north_3.png'), require('../assets/characters/boy_hiphop/animations/walking/north_4.png'), require('../assets/characters/boy_hiphop/animations/walking/north_5.png'), require('../assets/characters/boy_hiphop/animations/walking/north_6.png'), require('../assets/characters/boy_hiphop/animations/walking/north_7.png')],
      'north-west': [require('../assets/characters/boy_hiphop/animations/walking/north-west_0.png'), require('../assets/characters/boy_hiphop/animations/walking/north-west_1.png'), require('../assets/characters/boy_hiphop/animations/walking/north-west_2.png'), require('../assets/characters/boy_hiphop/animations/walking/north-west_3.png'), require('../assets/characters/boy_hiphop/animations/walking/north-west_4.png'), require('../assets/characters/boy_hiphop/animations/walking/north-west_5.png'), require('../assets/characters/boy_hiphop/animations/walking/north-west_6.png'), require('../assets/characters/boy_hiphop/animations/walking/north-west_7.png')],
      west: [require('../assets/characters/boy_hiphop/animations/walking/west_0.png'), require('../assets/characters/boy_hiphop/animations/walking/west_1.png'), require('../assets/characters/boy_hiphop/animations/walking/west_2.png'), require('../assets/characters/boy_hiphop/animations/walking/west_3.png'), require('../assets/characters/boy_hiphop/animations/walking/west_4.png'), require('../assets/characters/boy_hiphop/animations/walking/west_5.png'), require('../assets/characters/boy_hiphop/animations/walking/west_6.png'), require('../assets/characters/boy_hiphop/animations/walking/west_7.png')],
      'south-west': [require('../assets/characters/boy_hiphop/animations/walking/south-west_0.png'), require('../assets/characters/boy_hiphop/animations/walking/south-west_1.png'), require('../assets/characters/boy_hiphop/animations/walking/south-west_2.png'), require('../assets/characters/boy_hiphop/animations/walking/south-west_3.png'), require('../assets/characters/boy_hiphop/animations/walking/south-west_4.png'), require('../assets/characters/boy_hiphop/animations/walking/south-west_5.png'), require('../assets/characters/boy_hiphop/animations/walking/south-west_6.png'), require('../assets/characters/boy_hiphop/animations/walking/south-west_7.png')],
    },
  },
  boy_formal: {
    idle: {
      south: [require('../assets/characters/boy_formal/animations/idle/south_0.png'), require('../assets/characters/boy_formal/animations/idle/south_1.png'), require('../assets/characters/boy_formal/animations/idle/south_2.png'), require('../assets/characters/boy_formal/animations/idle/south_3.png')],
      'south-east': [require('../assets/characters/boy_formal/animations/idle/south-east_0.png'), require('../assets/characters/boy_formal/animations/idle/south-east_1.png'), require('../assets/characters/boy_formal/animations/idle/south-east_2.png'), require('../assets/characters/boy_formal/animations/idle/south-east_3.png')],
      east: [require('../assets/characters/boy_formal/animations/idle/east_0.png'), require('../assets/characters/boy_formal/animations/idle/east_1.png'), require('../assets/characters/boy_formal/animations/idle/east_2.png'), require('../assets/characters/boy_formal/animations/idle/east_3.png')],
      'north-east': [require('../assets/characters/boy_formal/animations/idle/north-east_0.png'), require('../assets/characters/boy_formal/animations/idle/north-east_1.png'), require('../assets/characters/boy_formal/animations/idle/north-east_2.png'), require('../assets/characters/boy_formal/animations/idle/north-east_3.png')],
      north: [require('../assets/characters/boy_formal/animations/idle/north_0.png'), require('../assets/characters/boy_formal/animations/idle/north_1.png'), require('../assets/characters/boy_formal/animations/idle/north_2.png'), require('../assets/characters/boy_formal/animations/idle/north_3.png')],
      'north-west': [require('../assets/characters/boy_formal/animations/idle/north-west_0.png'), require('../assets/characters/boy_formal/animations/idle/north-west_1.png'), require('../assets/characters/boy_formal/animations/idle/north-west_2.png'), require('../assets/characters/boy_formal/animations/idle/north-west_3.png')],
      west: [require('../assets/characters/boy_formal/animations/idle/west_0.png'), require('../assets/characters/boy_formal/animations/idle/west_1.png'), require('../assets/characters/boy_formal/animations/idle/west_2.png'), require('../assets/characters/boy_formal/animations/idle/west_3.png')],
      'south-west': [require('../assets/characters/boy_formal/animations/idle/south-west_0.png'), require('../assets/characters/boy_formal/animations/idle/south-west_1.png'), require('../assets/characters/boy_formal/animations/idle/south-west_2.png'), require('../assets/characters/boy_formal/animations/idle/south-west_3.png')],
    },
    walking: {
      south: [require('../assets/characters/boy_formal/animations/walking/south_0.png'), require('../assets/characters/boy_formal/animations/walking/south_1.png'), require('../assets/characters/boy_formal/animations/walking/south_2.png'), require('../assets/characters/boy_formal/animations/walking/south_3.png'), require('../assets/characters/boy_formal/animations/walking/south_4.png'), require('../assets/characters/boy_formal/animations/walking/south_5.png'), require('../assets/characters/boy_formal/animations/walking/south_6.png'), require('../assets/characters/boy_formal/animations/walking/south_7.png')],
      'south-east': [require('../assets/characters/boy_formal/animations/walking/south-east_0.png'), require('../assets/characters/boy_formal/animations/walking/south-east_1.png'), require('../assets/characters/boy_formal/animations/walking/south-east_2.png'), require('../assets/characters/boy_formal/animations/walking/south-east_3.png'), require('../assets/characters/boy_formal/animations/walking/south-east_4.png'), require('../assets/characters/boy_formal/animations/walking/south-east_5.png'), require('../assets/characters/boy_formal/animations/walking/south-east_6.png'), require('../assets/characters/boy_formal/animations/walking/south-east_7.png')],
      east: [require('../assets/characters/boy_formal/animations/walking/east_0.png'), require('../assets/characters/boy_formal/animations/walking/east_1.png'), require('../assets/characters/boy_formal/animations/walking/east_2.png'), require('../assets/characters/boy_formal/animations/walking/east_3.png'), require('../assets/characters/boy_formal/animations/walking/east_4.png'), require('../assets/characters/boy_formal/animations/walking/east_5.png'), require('../assets/characters/boy_formal/animations/walking/east_6.png'), require('../assets/characters/boy_formal/animations/walking/east_7.png')],
      'north-east': [require('../assets/characters/boy_formal/animations/walking/north-east_0.png'), require('../assets/characters/boy_formal/animations/walking/north-east_1.png'), require('../assets/characters/boy_formal/animations/walking/north-east_2.png'), require('../assets/characters/boy_formal/animations/walking/north-east_3.png'), require('../assets/characters/boy_formal/animations/walking/north-east_4.png'), require('../assets/characters/boy_formal/animations/walking/north-east_5.png'), require('../assets/characters/boy_formal/animations/walking/north-east_6.png'), require('../assets/characters/boy_formal/animations/walking/north-east_7.png')],
      north: [require('../assets/characters/boy_formal/animations/walking/north_0.png'), require('../assets/characters/boy_formal/animations/walking/north_1.png'), require('../assets/characters/boy_formal/animations/walking/north_2.png'), require('../assets/characters/boy_formal/animations/walking/north_3.png'), require('../assets/characters/boy_formal/animations/walking/north_4.png'), require('../assets/characters/boy_formal/animations/walking/north_5.png'), require('../assets/characters/boy_formal/animations/walking/north_6.png'), require('../assets/characters/boy_formal/animations/walking/north_7.png')],
      'north-west': [require('../assets/characters/boy_formal/animations/walking/north-west_0.png'), require('../assets/characters/boy_formal/animations/walking/north-west_1.png'), require('../assets/characters/boy_formal/animations/walking/north-west_2.png'), require('../assets/characters/boy_formal/animations/walking/north-west_3.png'), require('../assets/characters/boy_formal/animations/walking/north-west_4.png'), require('../assets/characters/boy_formal/animations/walking/north-west_5.png'), require('../assets/characters/boy_formal/animations/walking/north-west_6.png'), require('../assets/characters/boy_formal/animations/walking/north-west_7.png')],
      west: [require('../assets/characters/boy_formal/animations/walking/west_0.png'), require('../assets/characters/boy_formal/animations/walking/west_1.png'), require('../assets/characters/boy_formal/animations/walking/west_2.png'), require('../assets/characters/boy_formal/animations/walking/west_3.png'), require('../assets/characters/boy_formal/animations/walking/west_4.png'), require('../assets/characters/boy_formal/animations/walking/west_5.png'), require('../assets/characters/boy_formal/animations/walking/west_6.png'), require('../assets/characters/boy_formal/animations/walking/west_7.png')],
      'south-west': [require('../assets/characters/boy_formal/animations/walking/south-west_0.png'), require('../assets/characters/boy_formal/animations/walking/south-west_1.png'), require('../assets/characters/boy_formal/animations/walking/south-west_2.png'), require('../assets/characters/boy_formal/animations/walking/south-west_3.png'), require('../assets/characters/boy_formal/animations/walking/south-west_4.png'), require('../assets/characters/boy_formal/animations/walking/south-west_5.png'), require('../assets/characters/boy_formal/animations/walking/south-west_6.png'), require('../assets/characters/boy_formal/animations/walking/south-west_7.png')],
    },
  },
  girl_school: {
    idle: {
      south: [require('../assets/characters/girl_school/animations/idle/south_0.png'), require('../assets/characters/girl_school/animations/idle/south_1.png'), require('../assets/characters/girl_school/animations/idle/south_2.png'), require('../assets/characters/girl_school/animations/idle/south_3.png')],
      'south-east': [require('../assets/characters/girl_school/animations/idle/south-east_0.png'), require('../assets/characters/girl_school/animations/idle/south-east_1.png'), require('../assets/characters/girl_school/animations/idle/south-east_2.png'), require('../assets/characters/girl_school/animations/idle/south-east_3.png')],
      east: [require('../assets/characters/girl_school/animations/idle/east_0.png'), require('../assets/characters/girl_school/animations/idle/east_1.png'), require('../assets/characters/girl_school/animations/idle/east_2.png'), require('../assets/characters/girl_school/animations/idle/east_3.png')],
      'north-east': [require('../assets/characters/girl_school/animations/idle/north-east_0.png'), require('../assets/characters/girl_school/animations/idle/north-east_1.png'), require('../assets/characters/girl_school/animations/idle/north-east_2.png'), require('../assets/characters/girl_school/animations/idle/north-east_3.png')],
      north: [require('../assets/characters/girl_school/animations/idle/north_0.png'), require('../assets/characters/girl_school/animations/idle/north_1.png'), require('../assets/characters/girl_school/animations/idle/north_2.png'), require('../assets/characters/girl_school/animations/idle/north_3.png')],
      'north-west': [require('../assets/characters/girl_school/animations/idle/north-west_0.png'), require('../assets/characters/girl_school/animations/idle/north-west_1.png'), require('../assets/characters/girl_school/animations/idle/north-west_2.png'), require('../assets/characters/girl_school/animations/idle/north-west_3.png')],
      west: [require('../assets/characters/girl_school/animations/idle/west_0.png'), require('../assets/characters/girl_school/animations/idle/west_1.png'), require('../assets/characters/girl_school/animations/idle/west_2.png'), require('../assets/characters/girl_school/animations/idle/west_3.png')],
      'south-west': [require('../assets/characters/girl_school/animations/idle/south-west_0.png'), require('../assets/characters/girl_school/animations/idle/south-west_1.png'), require('../assets/characters/girl_school/animations/idle/south-west_2.png'), require('../assets/characters/girl_school/animations/idle/south-west_3.png')],
    },
    walking: {
      south: [require('../assets/characters/girl_school/animations/walking/south_0.png'), require('../assets/characters/girl_school/animations/walking/south_1.png'), require('../assets/characters/girl_school/animations/walking/south_2.png'), require('../assets/characters/girl_school/animations/walking/south_3.png'), require('../assets/characters/girl_school/animations/walking/south_4.png'), require('../assets/characters/girl_school/animations/walking/south_5.png'), require('../assets/characters/girl_school/animations/walking/south_6.png'), require('../assets/characters/girl_school/animations/walking/south_7.png')],
      'south-east': [require('../assets/characters/girl_school/animations/walking/south-east_0.png'), require('../assets/characters/girl_school/animations/walking/south-east_1.png'), require('../assets/characters/girl_school/animations/walking/south-east_2.png'), require('../assets/characters/girl_school/animations/walking/south-east_3.png'), require('../assets/characters/girl_school/animations/walking/south-east_4.png'), require('../assets/characters/girl_school/animations/walking/south-east_5.png'), require('../assets/characters/girl_school/animations/walking/south-east_6.png'), require('../assets/characters/girl_school/animations/walking/south-east_7.png')],
      east: [require('../assets/characters/girl_school/animations/walking/east_0.png'), require('../assets/characters/girl_school/animations/walking/east_1.png'), require('../assets/characters/girl_school/animations/walking/east_2.png'), require('../assets/characters/girl_school/animations/walking/east_3.png'), require('../assets/characters/girl_school/animations/walking/east_4.png'), require('../assets/characters/girl_school/animations/walking/east_5.png'), require('../assets/characters/girl_school/animations/walking/east_6.png'), require('../assets/characters/girl_school/animations/walking/east_7.png')],
      'north-east': [require('../assets/characters/girl_school/animations/walking/north-east_0.png'), require('../assets/characters/girl_school/animations/walking/north-east_1.png'), require('../assets/characters/girl_school/animations/walking/north-east_2.png'), require('../assets/characters/girl_school/animations/walking/north-east_3.png'), require('../assets/characters/girl_school/animations/walking/north-east_4.png'), require('../assets/characters/girl_school/animations/walking/north-east_5.png'), require('../assets/characters/girl_school/animations/walking/north-east_6.png'), require('../assets/characters/girl_school/animations/walking/north-east_7.png')],
      north: [require('../assets/characters/girl_school/animations/walking/north_0.png'), require('../assets/characters/girl_school/animations/walking/north_1.png'), require('../assets/characters/girl_school/animations/walking/north_2.png'), require('../assets/characters/girl_school/animations/walking/north_3.png'), require('../assets/characters/girl_school/animations/walking/north_4.png'), require('../assets/characters/girl_school/animations/walking/north_5.png'), require('../assets/characters/girl_school/animations/walking/north_6.png'), require('../assets/characters/girl_school/animations/walking/north_7.png')],
      'north-west': [require('../assets/characters/girl_school/animations/walking/north-west_0.png'), require('../assets/characters/girl_school/animations/walking/north-west_1.png'), require('../assets/characters/girl_school/animations/walking/north-west_2.png'), require('../assets/characters/girl_school/animations/walking/north-west_3.png'), require('../assets/characters/girl_school/animations/walking/north-west_4.png'), require('../assets/characters/girl_school/animations/walking/north-west_5.png'), require('../assets/characters/girl_school/animations/walking/north-west_6.png'), require('../assets/characters/girl_school/animations/walking/north-west_7.png')],
      west: [require('../assets/characters/girl_school/animations/walking/west_0.png'), require('../assets/characters/girl_school/animations/walking/west_1.png'), require('../assets/characters/girl_school/animations/walking/west_2.png'), require('../assets/characters/girl_school/animations/walking/west_3.png'), require('../assets/characters/girl_school/animations/walking/west_4.png'), require('../assets/characters/girl_school/animations/walking/west_5.png'), require('../assets/characters/girl_school/animations/walking/west_6.png'), require('../assets/characters/girl_school/animations/walking/west_7.png')],
      'south-west': [require('../assets/characters/girl_school/animations/walking/south-west_0.png'), require('../assets/characters/girl_school/animations/walking/south-west_1.png'), require('../assets/characters/girl_school/animations/walking/south-west_2.png'), require('../assets/characters/girl_school/animations/walking/south-west_3.png'), require('../assets/characters/girl_school/animations/walking/south-west_4.png'), require('../assets/characters/girl_school/animations/walking/south-west_5.png'), require('../assets/characters/girl_school/animations/walking/south-west_6.png'), require('../assets/characters/girl_school/animations/walking/south-west_7.png')],
    },
  },
  girl_casual: {
    idle: {
      south: [require('../assets/characters/girl_casual/animations/idle/south_0.png'), require('../assets/characters/girl_casual/animations/idle/south_1.png'), require('../assets/characters/girl_casual/animations/idle/south_2.png'), require('../assets/characters/girl_casual/animations/idle/south_3.png')],
      'south-east': [require('../assets/characters/girl_casual/animations/idle/south-east_0.png'), require('../assets/characters/girl_casual/animations/idle/south-east_1.png'), require('../assets/characters/girl_casual/animations/idle/south-east_2.png'), require('../assets/characters/girl_casual/animations/idle/south-east_3.png')],
      east: [require('../assets/characters/girl_casual/animations/idle/east_0.png'), require('../assets/characters/girl_casual/animations/idle/east_1.png'), require('../assets/characters/girl_casual/animations/idle/east_2.png'), require('../assets/characters/girl_casual/animations/idle/east_3.png')],
      'north-east': [require('../assets/characters/girl_casual/animations/idle/north-east_0.png'), require('../assets/characters/girl_casual/animations/idle/north-east_1.png'), require('../assets/characters/girl_casual/animations/idle/north-east_2.png'), require('../assets/characters/girl_casual/animations/idle/north-east_3.png')],
      north: [require('../assets/characters/girl_casual/animations/idle/north_0.png'), require('../assets/characters/girl_casual/animations/idle/north_1.png'), require('../assets/characters/girl_casual/animations/idle/north_2.png'), require('../assets/characters/girl_casual/animations/idle/north_3.png')],
      'north-west': [require('../assets/characters/girl_casual/animations/idle/north-west_0.png'), require('../assets/characters/girl_casual/animations/idle/north-west_1.png'), require('../assets/characters/girl_casual/animations/idle/north-west_2.png'), require('../assets/characters/girl_casual/animations/idle/north-west_3.png')],
      west: [require('../assets/characters/girl_casual/animations/idle/west_0.png'), require('../assets/characters/girl_casual/animations/idle/west_1.png'), require('../assets/characters/girl_casual/animations/idle/west_2.png'), require('../assets/characters/girl_casual/animations/idle/west_3.png')],
      'south-west': [require('../assets/characters/girl_casual/animations/idle/south-west_0.png'), require('../assets/characters/girl_casual/animations/idle/south-west_1.png'), require('../assets/characters/girl_casual/animations/idle/south-west_2.png'), require('../assets/characters/girl_casual/animations/idle/south-west_3.png')],
    },
    walking: {
      south: [require('../assets/characters/girl_casual/animations/walking/south_0.png'), require('../assets/characters/girl_casual/animations/walking/south_1.png'), require('../assets/characters/girl_casual/animations/walking/south_2.png'), require('../assets/characters/girl_casual/animations/walking/south_3.png'), require('../assets/characters/girl_casual/animations/walking/south_4.png'), require('../assets/characters/girl_casual/animations/walking/south_5.png'), require('../assets/characters/girl_casual/animations/walking/south_6.png'), require('../assets/characters/girl_casual/animations/walking/south_7.png')],
      'south-east': [require('../assets/characters/girl_casual/animations/walking/south-east_0.png'), require('../assets/characters/girl_casual/animations/walking/south-east_1.png'), require('../assets/characters/girl_casual/animations/walking/south-east_2.png'), require('../assets/characters/girl_casual/animations/walking/south-east_3.png'), require('../assets/characters/girl_casual/animations/walking/south-east_4.png'), require('../assets/characters/girl_casual/animations/walking/south-east_5.png'), require('../assets/characters/girl_casual/animations/walking/south-east_6.png'), require('../assets/characters/girl_casual/animations/walking/south-east_7.png')],
      east: [require('../assets/characters/girl_casual/animations/walking/east_0.png'), require('../assets/characters/girl_casual/animations/walking/east_1.png'), require('../assets/characters/girl_casual/animations/walking/east_2.png'), require('../assets/characters/girl_casual/animations/walking/east_3.png'), require('../assets/characters/girl_casual/animations/walking/east_4.png'), require('../assets/characters/girl_casual/animations/walking/east_5.png'), require('../assets/characters/girl_casual/animations/walking/east_6.png'), require('../assets/characters/girl_casual/animations/walking/east_7.png')],
      'north-east': [require('../assets/characters/girl_casual/animations/walking/north-east_0.png'), require('../assets/characters/girl_casual/animations/walking/north-east_1.png'), require('../assets/characters/girl_casual/animations/walking/north-east_2.png'), require('../assets/characters/girl_casual/animations/walking/north-east_3.png'), require('../assets/characters/girl_casual/animations/walking/north-east_4.png'), require('../assets/characters/girl_casual/animations/walking/north-east_5.png'), require('../assets/characters/girl_casual/animations/walking/north-east_6.png'), require('../assets/characters/girl_casual/animations/walking/north-east_7.png')],
      north: [require('../assets/characters/girl_casual/animations/walking/north_0.png'), require('../assets/characters/girl_casual/animations/walking/north_1.png'), require('../assets/characters/girl_casual/animations/walking/north_2.png'), require('../assets/characters/girl_casual/animations/walking/north_3.png'), require('../assets/characters/girl_casual/animations/walking/north_4.png'), require('../assets/characters/girl_casual/animations/walking/north_5.png'), require('../assets/characters/girl_casual/animations/walking/north_6.png'), require('../assets/characters/girl_casual/animations/walking/north_7.png')],
      'north-west': [require('../assets/characters/girl_casual/animations/walking/north-west_0.png'), require('../assets/characters/girl_casual/animations/walking/north-west_1.png'), require('../assets/characters/girl_casual/animations/walking/north-west_2.png'), require('../assets/characters/girl_casual/animations/walking/north-west_3.png'), require('../assets/characters/girl_casual/animations/walking/north-west_4.png'), require('../assets/characters/girl_casual/animations/walking/north-west_5.png'), require('../assets/characters/girl_casual/animations/walking/north-west_6.png'), require('../assets/characters/girl_casual/animations/walking/north-west_7.png')],
      west: [require('../assets/characters/girl_casual/animations/walking/west_0.png'), require('../assets/characters/girl_casual/animations/walking/west_1.png'), require('../assets/characters/girl_casual/animations/walking/west_2.png'), require('../assets/characters/girl_casual/animations/walking/west_3.png'), require('../assets/characters/girl_casual/animations/walking/west_4.png'), require('../assets/characters/girl_casual/animations/walking/west_5.png'), require('../assets/characters/girl_casual/animations/walking/west_6.png'), require('../assets/characters/girl_casual/animations/walking/west_7.png')],
      'south-west': [require('../assets/characters/girl_casual/animations/walking/south-west_0.png'), require('../assets/characters/girl_casual/animations/walking/south-west_1.png'), require('../assets/characters/girl_casual/animations/walking/south-west_2.png'), require('../assets/characters/girl_casual/animations/walking/south-west_3.png'), require('../assets/characters/girl_casual/animations/walking/south-west_4.png'), require('../assets/characters/girl_casual/animations/walking/south-west_5.png'), require('../assets/characters/girl_casual/animations/walking/south-west_6.png'), require('../assets/characters/girl_casual/animations/walking/south-west_7.png')],
    },
  },
  girl_career: {
    idle: {
      south: [require('../assets/characters/girl_career/animations/idle/south_0.png'), require('../assets/characters/girl_career/animations/idle/south_1.png'), require('../assets/characters/girl_career/animations/idle/south_2.png'), require('../assets/characters/girl_career/animations/idle/south_3.png')],
      'south-east': [require('../assets/characters/girl_career/animations/idle/south-east_0.png'), require('../assets/characters/girl_career/animations/idle/south-east_1.png'), require('../assets/characters/girl_career/animations/idle/south-east_2.png'), require('../assets/characters/girl_career/animations/idle/south-east_3.png')],
      east: [require('../assets/characters/girl_career/animations/idle/east_0.png'), require('../assets/characters/girl_career/animations/idle/east_1.png'), require('../assets/characters/girl_career/animations/idle/east_2.png'), require('../assets/characters/girl_career/animations/idle/east_3.png')],
      'north-east': [require('../assets/characters/girl_career/animations/idle/north-east_0.png'), require('../assets/characters/girl_career/animations/idle/north-east_1.png'), require('../assets/characters/girl_career/animations/idle/north-east_2.png'), require('../assets/characters/girl_career/animations/idle/north-east_3.png')],
      north: [require('../assets/characters/girl_career/animations/idle/north_0.png'), require('../assets/characters/girl_career/animations/idle/north_1.png'), require('../assets/characters/girl_career/animations/idle/north_2.png'), require('../assets/characters/girl_career/animations/idle/north_3.png')],
      'north-west': [require('../assets/characters/girl_career/animations/idle/north-west_0.png'), require('../assets/characters/girl_career/animations/idle/north-west_1.png'), require('../assets/characters/girl_career/animations/idle/north-west_2.png'), require('../assets/characters/girl_career/animations/idle/north-west_3.png')],
      west: [require('../assets/characters/girl_career/animations/idle/west_0.png'), require('../assets/characters/girl_career/animations/idle/west_1.png'), require('../assets/characters/girl_career/animations/idle/west_2.png'), require('../assets/characters/girl_career/animations/idle/west_3.png')],
      'south-west': [require('../assets/characters/girl_career/animations/idle/south-west_0.png'), require('../assets/characters/girl_career/animations/idle/south-west_1.png'), require('../assets/characters/girl_career/animations/idle/south-west_2.png'), require('../assets/characters/girl_career/animations/idle/south-west_3.png')],
    },
    walking: {
      south: [require('../assets/characters/girl_career/animations/walking/south_0.png'), require('../assets/characters/girl_career/animations/walking/south_1.png'), require('../assets/characters/girl_career/animations/walking/south_2.png'), require('../assets/characters/girl_career/animations/walking/south_3.png'), require('../assets/characters/girl_career/animations/walking/south_4.png'), require('../assets/characters/girl_career/animations/walking/south_5.png'), require('../assets/characters/girl_career/animations/walking/south_6.png'), require('../assets/characters/girl_career/animations/walking/south_7.png')],
      'south-east': [require('../assets/characters/girl_career/animations/walking/south-east_0.png'), require('../assets/characters/girl_career/animations/walking/south-east_1.png'), require('../assets/characters/girl_career/animations/walking/south-east_2.png'), require('../assets/characters/girl_career/animations/walking/south-east_3.png'), require('../assets/characters/girl_career/animations/walking/south-east_4.png'), require('../assets/characters/girl_career/animations/walking/south-east_5.png'), require('../assets/characters/girl_career/animations/walking/south-east_6.png'), require('../assets/characters/girl_career/animations/walking/south-east_7.png')],
      east: [require('../assets/characters/girl_career/animations/walking/east_0.png'), require('../assets/characters/girl_career/animations/walking/east_1.png'), require('../assets/characters/girl_career/animations/walking/east_2.png'), require('../assets/characters/girl_career/animations/walking/east_3.png'), require('../assets/characters/girl_career/animations/walking/east_4.png'), require('../assets/characters/girl_career/animations/walking/east_5.png'), require('../assets/characters/girl_career/animations/walking/east_6.png'), require('../assets/characters/girl_career/animations/walking/east_7.png')],
      'north-east': [require('../assets/characters/girl_career/animations/walking/north-east_0.png'), require('../assets/characters/girl_career/animations/walking/north-east_1.png'), require('../assets/characters/girl_career/animations/walking/north-east_2.png'), require('../assets/characters/girl_career/animations/walking/north-east_3.png'), require('../assets/characters/girl_career/animations/walking/north-east_4.png'), require('../assets/characters/girl_career/animations/walking/north-east_5.png'), require('../assets/characters/girl_career/animations/walking/north-east_6.png'), require('../assets/characters/girl_career/animations/walking/north-east_7.png')],
      north: [require('../assets/characters/girl_career/animations/walking/north_0.png'), require('../assets/characters/girl_career/animations/walking/north_1.png'), require('../assets/characters/girl_career/animations/walking/north_2.png'), require('../assets/characters/girl_career/animations/walking/north_3.png'), require('../assets/characters/girl_career/animations/walking/north_4.png'), require('../assets/characters/girl_career/animations/walking/north_5.png'), require('../assets/characters/girl_career/animations/walking/north_6.png'), require('../assets/characters/girl_career/animations/walking/north_7.png')],
      'north-west': [require('../assets/characters/girl_career/animations/walking/north-west_0.png'), require('../assets/characters/girl_career/animations/walking/north-west_1.png'), require('../assets/characters/girl_career/animations/walking/north-west_2.png'), require('../assets/characters/girl_career/animations/walking/north-west_3.png'), require('../assets/characters/girl_career/animations/walking/north-west_4.png'), require('../assets/characters/girl_career/animations/walking/north-west_5.png'), require('../assets/characters/girl_career/animations/walking/north-west_6.png'), require('../assets/characters/girl_career/animations/walking/north-west_7.png')],
      west: [require('../assets/characters/girl_career/animations/walking/west_0.png'), require('../assets/characters/girl_career/animations/walking/west_1.png'), require('../assets/characters/girl_career/animations/walking/west_2.png'), require('../assets/characters/girl_career/animations/walking/west_3.png'), require('../assets/characters/girl_career/animations/walking/west_4.png'), require('../assets/characters/girl_career/animations/walking/west_5.png'), require('../assets/characters/girl_career/animations/walking/west_6.png'), require('../assets/characters/girl_career/animations/walking/west_7.png')],
      'south-west': [require('../assets/characters/girl_career/animations/walking/south-west_0.png'), require('../assets/characters/girl_career/animations/walking/south-west_1.png'), require('../assets/characters/girl_career/animations/walking/south-west_2.png'), require('../assets/characters/girl_career/animations/walking/south-west_3.png'), require('../assets/characters/girl_career/animations/walking/south-west_4.png'), require('../assets/characters/girl_career/animations/walking/south-west_5.png'), require('../assets/characters/girl_career/animations/walking/south-west_6.png'), require('../assets/characters/girl_career/animations/walking/south-west_7.png')],
    },
  },
}
